version: "3"
services:
  app:
    image: "525140287988.dkr.ecr.eu-west-1.amazonaws.com/moneteer/backend/app:latest"
    ports:
      - "5000:5000"
    logging:
      driver: "awslogs"
      options:
        awslogs-region: "eu-west-1"
        awslogs-group: "moneteer.backend.app"
        awslogs-stream-prefix: "app"
        awslogs-multiline-pattern: '^....:\s'
  proxy:
    image: "525140287988.dkr.ecr.eu-west-1.amazonaws.com/moneteer/backend/proxy:latest"
    ports:
      - "80:80"
      - "8080:8080"
    logging:
      driver: "awslogs"
      options:
        awslogs-region: "eu-west-1"
        awslogs-group: "moneteer.backend.proxy"
        awslogs-stream-prefix: "proxy"

# Create the service using the default cluster profile
# ecs-cli compose -f docker-compose-backend-aws-production.yml service up --target-group-arn arn:aws:elasticloadbalancing:eu-west-1:525140287988:targetgroup/ecs-moneteer-backend-service/e841cb5ea4a3607b --container-name proxy --container-port 80

# Force a new deployment. Used when the service definition doesn't change but you want to update the image
# aws ecs update-service --cluster moneteer-cluster --service moneteer-backend --force-new-deployment